#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

apt-get update
apt-get install -y nginx

#creating a 404 error page
echo "Ceci n'est pas une page" /etc/nginx/html/404.html | sudo tee /var/www/html/404.html
Replacement_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$Replacement_string/" /etc/nginx/sites-enabled/default
service nginx restart
